### ISSUE TITLE
Issue w/ Tetra workbench - Will not display the 'basic handle' option in 0.4.9. in singleplayer world for double headed tools

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica5#282]
**Modpack version**
0.4.9

**Issue**
Will not display the 'basic handle' option in 0.4.9. in singleplayer world for double headed tools. Tested using twitch download, GD import, using singleplayer world created directly in 0.4.9.
Reported originally by Dura.

Worked correct in an instance created w/ just Tetra and mgui. 

The_boo tested on E5 server and was unable to replicate the issue.
![2020-05-07_20 57 06](https://user-images.githubusercontent.com/10382598/81360057-d45d2100-90a8-11ea-87a1-99012c3a96c7.png)

**Comment by Trostmm** [comment]
tried the following combinations -

Twitch - 0.4.9, New world, singleplayer - Did not function normally, per SS.
GDlauncher - Imported 0.4.9 from Curseforge, New world, singlepalyer - Did not function normally, per SS.
GDlauncher - New forge instance using 31.1.63, installed just Tetra 1.15.2-2.5.0 and mgui 1.15.2-2.1.1 - New world, singleplayer - Functioned correctly.
E5 Server - 0.4.9 - Existing workbench, Functioned correctly, New workbench, functioned correctly.

*shrug*

**Comment by NielsPilgaard** [comment]
Hmm, I think I've encountered that issue before, I'll try to pin it down. Do you have any thoughts @Mickelus?

**Comment by wagnerwj** [comment]
So- further reporting...
I took a fresh 0.4.8 instance through Twich- built a world out until I got Level 2 Tetra Hammers... then saved and upgraded through Twitch.

On restart- I got the warning "Registry entry was missing"- then on play the option to change the handle wasn't there...

**Comment by mickelus** [comment]
I'm guessing there's some missing/faulty material for one of the handles, but it's difficult to say without seeing the logs!

**Comment by Trostmm** [comment]
> I'm guessing there's some missing/faulty material for one of the handles, but it's difficult to say without seeing the logs!

Is there any log I could generate to assist? I kept the instances I have where it isn't working pe rmy above testing.

**Comment by NielsPilgaard** [comment]
I think I messed up the datapack for `modules/double/basic_handle.json`
```json
{
    "variants": [
        {
            "key": "basic_handle/ancient_wood",
            "durability": 20,
            "integrity": 5,
            "magicCapacity": 17,
            "attackSpeed": 0.35,
            "glyph": {
                "tint": "723957",
                "textureX": 16
            },
            "models": [
                {
                    "location": "tetra:items/module/sword/hilt/basic/default",
                    "tint": "723957"
                }
            ]
        }
    ]
}
```

**Comment by wagnerwj** [comment]
I changed schemas/double/basic_handle/basic_handle.json, and that worked.

**Comment by NielsPilgaard** [comment]
Awesome, in that case this issue is solved in the next update :)

**Comment by theboo** [comment]
is not fixed for me in a brand new world on 0.4.10...

looke like it is still calling duplex instead of double in your data pack for the basic handle.

```{
    "outcomes": [
        {
            "material": {
                "tag": "forge:planks/ancient"
            },
            "requiredCapabilities": {
                "axe": 3
            },
            "moduleKey": "duplex/basic_handle",
            "moduleVariant": "basic_handle/ancient_wood"
        }
    ]
}
```


https://gyazo.com/e9de3f89110f38d2f7a81545c7099197

<blockquote><img src="https://i.gyazo.com/thumb/1200/e9de3f89110f38d2f7a81545c7099197-png.jpg" width="48" align="right"><div><img src="https://assets.gyazo.com/favicon.ico" height="14"> Gyazo</div><div><strong><a href="https://gyazo.com/e9de3f89110f38d2f7a81545c7099197">Gyazo</a></strong></div><div>&nbsp;</div></blockquote>

**Comment by theboo** [comment]
just noticed... somehow the datapack you removed is still in 0.4.10

**Comment by NielsPilgaard** [comment]
Oh right, I forgot stuff doesn't get deleted ><

**Comment by NielsPilgaard** [comment]
Huh, my play instance updated just fine, removed the datapack jsons.
